{% set name = "piou" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Andarius/piou/archive/refs/tags/{{ version }}.tar.gz
  sha256: a8b9b9f847ee2baf9082f36c16493b084bb66a292a3e5303a24ad6d6c210ecde


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9,<4.0
    - pip
    - poetry
  run:
    - python >=3.9,<4.0
    - rich >=10.11.0

test:
  requires:
    - pip
  commands:
    - pip check
    - python -m piou.test
  imports:
    - piou
about:
  home: https://github.com/Andarius/piou
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CLI tool to build beautiful command-line interfaces with type validation
  dev_url: https://github.com/Andarius/piou
  doc_url: https://github.com/Andarius/piou

extra:
  recipe-maintainers:
    - andarius
