{% set name = "piou" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Andarius/piou/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4f087a106a6b39fa64e461a3db09c8802e01919102f14da21f35ae59a6702410


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9,<4.0
    - pip
    - poetry
  run:
    - python >=3.9,<4.0
    - rich >=10.11.0

test:
  requires:
    - pip
  commands:
    - pip check
    - python -m piou.test -h
  imports:
    - piou
about:
  home: https://github.com/Andarius/piou
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CLI tool to build beautiful command-line interfaces with type validation
  dev_url: https://github.com/Andarius/piou
  doc_url: https://github.com/Andarius/piou

extra:
  recipe-maintainers:
    - andarius
